Improved resampling checks
AI4S2S/lilio pull request #39
Opened 2023-02-09 14:03 UTC by BSchilperoort

In this PR:

- A robust check for frequency mismatch between the data and calendar is implemented (closes #10).
- Removed pytest.fixture(autouse=True), it was used incorrectly, and lead to over-testing. 
- Resampling is changed so if the user inputs a DataArray, they get a DataArray back.
  - This lead to a change in the definition of "bounds" of the resampling output. Instead of "interval" with dims (anchor_year, i_interval, bounds), there are now two coords (left_bound and right_bound) with dims (anchor_year, i_interval). This change was required to preserve the interval datetimes in the DataArray output.

2023-02-09 15:28 UTC, BSchilperoort commented
Hm. Turns out that there's a problem with the traintest notebook. I think we'll have to check the xarray/pandas input data for reserved coordinate/column names, e.g.:

anchor_year, i_interval, left_bound, right_bound, is_target (rename from "target").

An error should be raised if the data already contains one or more of these

2023-02-10 15:13 UTC, geek-yang requested changes
Nice work! The changes look nice and they help a lot to improve the "quality of life". Only got two small points:

- In `utils.py`, we have defined 
```py
PandasData = (pd.Series, pd.DataFrame)
XArrayData = (xr.DataArray, xr.Dataset)
```
But they are not used in some places. It would be nice to either use them when they could be applied, or just delete them and use the pandas and xarray object type.

- The checks for frequency works for most of the cases, but not for monthly calendar (see the minimum example below)

2023-02-10 15:15 UTC, geek-yang commented
The checks for frequency works for most of the cases, but not for monthly calendar, for instance

```py
time_index = pd.date_range("20181001", "20211001", freq="2M")
df = pd.DataFrame(
    data={
        "data1": np.random.random(len(time_index)),
    },
    index=time_index,
)

cal = monthly_calendar(anchor="10-15", length="1M")
cal = cal.map_to_data(df)
lilio.resample(cal, df)
```
This will throw the following warning messages, which indeed have nothing to do with frequency, but only NaN values.
```py
/home/yangliu/AI4S2S/lilio/lilio/utils.py:104: FutureWarning: Units 'M', 'Y' and 'y' do not represent unambiguous timedelta values and will be removed in a future version.
  return pd.Timedelta(data_freq)
/home/yangliu/miniconda3/envs/s2spy/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/yangliu/miniconda3/envs/s2spy/lib/python3.10/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/yangliu/AI4S2S/lilio/lilio/utils.py:80: UserWarning: The input data could not fully cover the calendar's intervals. Intervals without available data will contain NaN values.
  warnings.warn(
```

As we have provided `monthly_calendar` in the shorthands, it would be nice to have check for it as well.

2023-02-15 07:14 UTC, BSchilperoort commented on lilio/utils.py
> +    }
It should be visible in the HTML representation, as well as in a NetCDF file. We probably should add more attr info to the calendar resample output, such as storing the calendar used to generate it.

2023-02-15 07:23 UTC, BSchilperoort commented on lilio/utils.py
> +    if not isinstance(data, (pd.Series, pd.DataFrame, xr.DataArray, xr.Dataset)):
I've decided to stop using the aliases, it does not save that much code, can make it less clear for what is happening, and I don't like them that much in the auto api docs.

I now removed PandasData and XArrayData everywhere in lilio.

2023-02-15 07:28 UTC, BSchilperoort commented
> The checks for frequency works for most of the cases, but not for monthly calendar, for instance

Thanks for spotting this bug, Yang. It turns out that the Calendar's frequency is checked correctly, but the data's frequency is not! I'll modify the check to account for monthly-freq data inputs.

2023-02-15 12:34 UTC, merged